kind: Service
apiVersion: v1
metadata:
  name: k8s-master
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: k8s
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    component: k8s-master